config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/about_us' => 'pages#about_us'

  get '/log_in' => 'pages#log_in'

  resources :transactions
  resources :users

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

	validates :amount, presence: true
	validates :classify, presence: true
	validates :category, presence: true
	validates :posted_on, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@transactions = Transaction.all.reverse
  	@last = 0
  	@tentransactions = Transaction.last(10).reverse
    @transactions.each do |transaction|

		if (transaction.classify == "Income")
			@last += transaction.amount
		else 
		    @last -= transaction.amount
		end
	end
	if Transaction.last != nil
		@totalbalance = Transaction.last.totalbalance
	else
		@totalbalance =0
	end
  end

  def about_us
  	render 'about_us'
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @transactions = Transaction.all.reverse
    @last = 0
    @tentransactions = Transaction.last(10).reverse
    @transactions.each do |transaction|

    if (transaction.classify == "Income")
      @last += transaction.amount
    else 
        @last -= transaction.amount
    end
  end
  if Transaction.last != nil
  @totalbalance = Transaction.last.totalbalance
  end
  end

  def new
  	@transaction = Transaction.new
  end

  def create
  	@transaction = Transaction.new
  	@transaction.amount = params[:transaction][:amount]
  	@transaction.classify = params[:transaction][:classify]
  	@transaction.category = params[:transaction][:category]
  	@transaction.description = params[:transaction][:description]
  	@transaction.posted_on = DateTime.now
    if Transaction.last != nil
      if (@transaction.classify == "Income")
        @transaction.totalbalance = Transaction.last.totalbalance + @transaction.amount
      else 
        @transaction.totalbalance = Transaction.last.totalbalance - @transaction.amount
      end
    else
      if @transaction.classify == "Income"
        @transaction.totalbalance = @transaction.amount
      else
        @transaction.totalbalance = 0 - @transaction.amount
      end
    end
    @totalbalance = @transaction.totalbalance
    @transaction.save!
  	redirect_to root_path
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy!

    redirect_to root_path
  end

  def edit
    @transaction = Transaction.find(params[:id])

  end

  def update
    @transaction = Transaction.find(params[:id])
    @last= 0
    @transaction.totalbalance = 0
    @transaction.amount = params[:transaction][:amount]
    @transaction.classify = params[:transaction][:classify]
    @transaction.category = params[:transaction][:category]
    @transaction.description = params[:transaction][:description]
    @transaction.posted_on = DateTime.now
    @transaction.save!
    Transaction.all.each do |transaction|
      if (transaction.classify == "Income")
        @last += transaction.amount
      else 
        @last -= transaction.amount
      end
      transaction.save!
    end
    @totalbalance = @transaction.totalbalance
    

    redirect_to root_path
  end

  def show
    @transaction = Transaction.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.new
    @user.first_name = params [:user][:first_name]
    @user.last_name = params [:user][:last_name]
    @user.email = params [:user][:email]
    @user.password = params [:user][:password]
    @user.save!

    redirect_to :action => :index
  end

  def new
    @user = User.new
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!

    redirect_to :action => :index
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Wallet - Online App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about_us.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Carlos Alvarez, Theme designer & developer living in Madrid, Spain.">
    <meta name="author" content="Carlos Alvarez">
    <link rel="shortcut icon" href="ico/favicon.png">

    <title>About Us : App Creators</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="/css/main.css" rel="stylesheet">
    
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <link href = "/css/mystyle.css" rel="stylesheet">
    

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
    tbody tr:nth-child(even)
    {
		background: lightblue;
    }
    tbody tr:hover
    {
    		background: #31a3b0;
    		color: white;
    }
    body
    {
    	background-image:url("/assets/bg.jpg"); 
    	background-repeat:no-repeat;
    	background-attachment:fixed;
    	background-position:center;
    	text-align:center;
		background-color:lightblue;
	   	-webkit-background-size: cover;
		-moz-background-size: cover;
	   	-o-background-size: cover;
	   	background-size: cover;
    }
    h3
    {
    	text-align:center;
		margin:0 auto;
		padding:20px;
		width:900px;
		background-color:lightblue;
		opacity:1;
		filter:alpha(opacity=100);
    }

    </style>
  </head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <strong /><a class="navbar-brand" href=" " >My Wallet &nbsp;&nbsp;<%= image_tag "20.png", size: "50x39" %></a><!-- this is where you set the navigation title -->
        </div>
        <div class="collapse navbar-collapse"><!-- collapse allows for this navbar to be used in mobile devices -->
          <ul class="nav navbar-nav"><!-- this is the list of navigation options in your navbar -->
            <li><a href="/">Home</a></li>
            <li><a href="/transactions">Records</a></li>
            <li><a class="active" href="/about_us">About Us</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2 w">
        <div>
          <br />
          <h1>About: MyWallet &nbsp;&nbsp; <%= image_tag "50.png", size: "160x126" %></h1>
          <br/>
          <h2><a href="https://www.facebook.com/erikareyes695" title="Erika Reyes"><%= image_tag "erika.png" %></a> &nbsp;&nbsp;&nbsp; <a href="https://www.facebook.com/danping.cai" title="Dan Ping Cai"><%= image_tag "dp.png" %></a></h2>
          <br />
          <div id = "bg">
          <h3 id = "text">MyWallet is a user-friendly application for tracking your income and expenses. See where every peso goes and make money decisions you feel good about!</h4>
          <h3>Contact Us @ the links provided below! :)</h3>
        </div>
        </div>
      </div>
    </div>

    	<div class="row centered">
			<div class="col-lg-8 col-lg-offset-2 w tooltip-demo">
				<a data-toggle="tooltip" title="Facebook" href="https://www.facebook.com/erikareyes695"><i class="fa fa-facebook"></i></a>
				<a data-toggle="tooltip" title="Twitter" href="https://twitter.com/dpcai_1023"><i class="fa fa-twitter"></i></a>
				<a data-toggle="tooltip" title="Call Us" href="#"><i class="fa fa-phone"></i></a>
				<a data-toggle="tooltip" title="Free Themes" href="http://BlackTie.co"><i class="fa fa-heart"></i></a>
				<a data-toggle="tooltip" title="Blog" href="#"><i class="fa fa-comment"></i></a>
				<a data-toggle="tooltip" title="Email Me!" href="http://mail.yahoo.com/"><i class="fa fa-envelope"></i></a>
				<a data-toggle="tooltip" title="Newsletter" href="http://eepurl.com/"><i class="fa fa-coffee"></i></a>
			</div>
		</div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script>
    $('.tooltip-demo').tooltip({
      selector: "[data-toggle=tooltip]",
      container: "body"
    })
  </script>


    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="/js/jquery.backstretch.min.js"></script>
    <script>
        $.backstretch("bg.jpg", {speed: 500});
    </script>
	</body>
</html>

app/views/pages/index.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Carlos Alvarez, Theme designer & developer living in Madrid, Spain.">
    <meta name="author" content="Carlos Alvarez">
    <link rel="shortcut icon" href="ico/favicon.png">

    <title>My Wallet - Online App</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="/css/main.css" rel="stylesheet">
    
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <link href = "/css/mystyle.css" rel="stylesheet">
    

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
    tbody tr:nth-child(even)
    {
		background: lightblue;
    }
    tbody tr:hover
    {
    		background: #31a3b0;
    		color: white;
    }
    body
    {
    	background-image:url("/assets/bg.jpg"); 
    	background-repeat:no-repeat;
    	background-attachment:fixed;
    	background-position:center;
    	text-align:center;
		background-color:lightblue;
	   	-webkit-background-size: cover;
		-moz-background-size: cover;
	   	-o-background-size: cover;
	   	background-size: cover;
    }
    </style>
  </head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <strong /><a class="navbar-brand" href=" " >My Wallet &nbsp;&nbsp;<%= image_tag "20.png", size: "50x39" %></a><!-- this is where you set the navigation title -->
        </div>
        <div class="collapse navbar-collapse"><!-- collapse allows for this navbar to be used in mobile devices -->
          <ul class="nav navbar-nav"><!-- this is the list of navigation options in your navbar -->
            <li><a class="active" href="/">Home</a></li>
            <li><a href="/transactions">Records</a></li>
            <li><a href="/about_us">About Us</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
  		<div class="row centered">
  			<div class="col-lg-8 col-lg-offset-2 w">
	            <div>
	            	<br/>
	            	<h1> MyWallet &nbsp;&nbsp; <%= image_tag "50.png", size: "160x126" %></h1>
	            </div>
	            <br/>
          		<center>
          			<div>
						<strong><h3>Total Balance: </h3>
						<h2>Php <%= @last %></h2>
						<br/>
					</div>

					<div>
						<table class = "table">
							<thread>
								<tr class="head">
									<td>Amount</td>
									<td>Type of Transaction</td>
									<td>Category</td>
									<td>Description</td>
									<td>Date Posted</td>
									<td></td>
									<td></td>
								</tr>
							</thread>
							<tbody>
								<% @tentransactions.each do |transaction| %>
								<tr>
									<td>Php <%= transaction.amount %></td>
									<td><%= transaction.classify %></td>
									<td><%= transaction.category %></td>
									<td><%= transaction.description %></td>
									<td><%= transaction.posted_on %></td>
									<td><%= link_to "Edit", edit_transaction_path(transaction) %></td>
								<td><%=link_to "Delete", transaction_path(transaction), :method => :delete, :class => "delete", :confirm => "Are you sure ?"%></td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</div>
          		</center>
          		<br />
          		<a href="/transactions" class="btn btn-default">..More Transaction Records</a>
          		<a href="/transactions/new" class="btn btn-default">Create a New Transaction</a>
  			</div>
  		</div>
		<div class="row centered">
			<div class="col-lg-8 col-lg-offset-2 w tooltip-demo">
				<a data-toggle="tooltip" title="Facebook" href="https://www.facebook.com/erikareyes695"><i class="fa fa-facebook"></i></a>
				<a data-toggle="tooltip" title="Twitter" href="https://twitter.com/dpcai_1023"><i class="fa fa-twitter"></i></a>
				<a data-toggle="tooltip" title="Call Us" href="#"><i class="fa fa-phone"></i></a>
				<a data-toggle="tooltip" title="Free Themes" href="http://BlackTie.co"><i class="fa fa-heart"></i></a>
				<a data-toggle="tooltip" title="Blog" href="#"><i class="fa fa-comment"></i></a>
				<a data-toggle="tooltip" title="Email Me!" href="http://mail.yahoo.com/"><i class="fa fa-envelope"></i></a>
				<a data-toggle="tooltip" title="Newsletter" href="http://eepurl.com/"><i class="fa fa-coffee"></i></a>
			</div>
		</div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script>
    $('.tooltip-demo').tooltip({
      selector: "[data-toggle=tooltip]",
      container: "body"
    })
	</script>


    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="/js/jquery.backstretch.min.js"></script>
    <script>
        $.backstretch("/assets/bg.jpg", {speed: 500});
    </script>

  </body>
</html>

app/views/pages/log_in.html.erb
<h1>Pages#log_in</h1>
<p>Find me in app/views/pages/log_in.html.erb</p>

<p><%= link_to 'Home', root_path %></p>
<p><%= link_to 'About Us', about_us_path %></p>
<p><%= link_to 'Log-in', log_in_path %></p>
<p><%= link_to 'Sign-up', sign_up_path %></p>

app/views/pages/sign_up.html.erb
<h1>Pages#sign_up</h1>
<p>Find me in app/views/pages/sign_up.html.erb</p>

<p><%= link_to 'Home', root_path %></p>
<p><%= link_to 'About Us', about_us_path %></p>
<p><%= link_to 'Log-in', log_in_path %></p>
<p><%= link_to 'Sign-up', sign_up_path %></p>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

<p><%= debug @transaction %></p>

app/views/transactions/index.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Carlos Alvarez, Theme designer & developer living in Madrid, Spain.">
    <meta name="author" content="Carlos Alvarez">
    <link rel="shortcut icon" href="ico/favicon.png">

    <title>My Transaction Records</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="/css/main.css" rel="stylesheet">
    
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "mystyle", media: 'all' %>
    

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
    tbody tr:nth-child(even)
    {
		background: lightblue;
    }
    tbody tr:hover
    {
    		background: #31a3b0;
    		color: white;
    }
    body
    {
    	background-image:url("/assets/bg.jpg"); 
    	background-repeat:no-repeat;
    	background-attachment:fixed;
    	background-position:center;
    	text-align:center;
		background-color:lightblue;
	   	-webkit-background-size: cover;
		-moz-background-size: cover;
	   	-o-background-size: cover;
	   	background-size: cover;
    }

    </style>

  </head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <strong /><a class="navbar-brand" href=" " >My Wallet &nbsp;&nbsp;<%= image_tag "20.png", size: "50x39" %></a><!-- this is where you set the navigation title -->
        </div>
        <div class="collapse navbar-collapse"><!-- collapse allows for this navbar to be used in mobile devices -->
          <ul class="nav navbar-nav"><!-- this is the list of navigation options in your navbar -->
            <li><a href="/">Home</a></li>
            <li><a class="active" href="/transactions">Records</a></li>
            <li><a href="/about_us">About Us</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
  		<div class="row centered">
  			<div class="col-lg-8 col-lg-offset-2 w">
	            <div id = "banner">
	            	<br/>
	            	<h1>All Records &nbsp;&nbsp; <%= image_tag "50.png", size: "160x126" %></h1>
	            </div>
	            <br/><br/>
          		<center>
          			<div>
						<strong><h3>Total Balance: </h3>
						<h2>Php <%= @last %></h2>
						<br/>
					</div>

					<div>
						<table class = "table">
							<thread>
								<tr>
									<td>Amount</td>
									<td>Type of Transaction</td>
									<td>Category</td>
									<td>Description</td>
									<td>Date Posted</td>
									<td></td>
									<td></td>
								</tr>
							</thread>
							<tbody>
								<% @transactions.each do |transaction| %>
								<tr>
									<td><%= transaction.amount %></td>
									<td><%= transaction.classify %></td>
									<td><%= transaction.category %></td>
									<td><%= transaction.description %></td>
									<td><%= transaction.posted_on %></td>
									<td><%= link_to "Edit", edit_transaction_path(transaction) %></td>
								<td><%=link_to "Delete", transaction_path(transaction), :method => :delete, :class => "delete", :confirm => "Are you sure ?"%></td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</div>
          		</center>
          		<br />
          		<a href="/transactions/new" class="btn btn-default">Create a New Transaction</a>
  			</div>
  		</div>
		<div class="row centered">
			<div class="col-lg-8 col-lg-offset-2 w tooltip-demo">
				<a data-toggle="tooltip" title="Facebook" href="https://www.facebook.com/erikareyes695"><i class="fa fa-facebook"></i></a>
				<a data-toggle="tooltip" title="Twitter" href="https://twitter.com/dpcai_1023"><i class="fa fa-twitter"></i></a>
				<a data-toggle="tooltip" title="Call Us" href="#"><i class="fa fa-phone"></i></a>
				<a data-toggle="tooltip" title="Free Themes" href="http://BlackTie.co"><i class="fa fa-heart"></i></a>
				<a data-toggle="tooltip" title="Blog" href="#"><i class="fa fa-comment"></i></a>
				<a data-toggle="tooltip" title="Email Me!" href="http://mail.yahoo.com/"><i class="fa fa-envelope"></i></a>
				<a data-toggle="tooltip" title="Newsletter" href="http://eepurl.com/"><i class="fa fa-coffee"></i></a>
			</div>
		</div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>

    <script>
    $('.tooltip-demo').tooltip({
      selector: "[data-toggle=tooltip]",
      container: "body"
    })
	</script>


    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="/js/jquery.backstretch.min.js"></script>
    <script>
        $.backstretch("/img/bg.jpg", {speed: 500});
    </script>

  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>